### ISSUE TITLE
Adicionar arquivo de configuração do scrutinizer

### ISSUE THREAD

**Issue by MarceloCajueiro** [portabilis/i-educar#233]
Objetivo: fazer o serviço rodar da melhor forma possível para o projeto.

Referência para quem for fazer: https://github.com/portabilis/i-educar/pull/211#pullrequestreview-127415069

Link do scrutinizer: https://scrutinizer-ci.com/g/portabilis/i-educar/inspections/396936a9-37ad-42df-a81c-804eaac68f78

**Comment by farribeiro** [comment]
eu posso fazer um cherry pick do commits do @williamespindola e abrir um PR daquelas alterações

**Comment by MarceloCajueiro** [comment]
Acho Ok, mas tem que ser commits separados. Cada PR resolvendo um problema.

**Comment by farribeiro** [comment]
Isso não é necessário, olhe para seus branches cheios de commiters variados

**Comment by williamespindola** [comment]
Da para ficar apenas um commit, basta fazer amend no meu commit. Manda bala @farribeiro se precisar de ajuda da um grito.

**Comment by williamespindola** [comment]
Da para usar o do pr #211 tranquilamente, basta adicionar o trecho que o Cajueiro falou:
```
- 'ieducar/tests/*'
- 'ieducar/misc/**/*'
```

e @MarceloCajueiro não tem problema eles ficaram red até estarem passando. Isto é bom naverdade pois da para ver onde precisamos atacar.

**Comment by williamespindola** [comment]
Se não quiser pegar do PR pode copiar daqui também
```
filter:
    excluded_paths:
        - tests/*

checks:
    php:
        code_rating: true

tools:
    external_code_coverage: true
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true
```
